project:
  type: website
  output-dir: docs

render:
  - index.qmd
  - pages/pssi/*.qmd
  - pages/bcsrif/*.qmd

website:
  title: "Pacific Salmon Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
  search: true  # Enable search functionality
  page-footer:
    right: "Author: PSSI Implementation Team"

format:
  html:
    css: styles.css
    theme: default
    page-layout: full        # Enables full-width content
    grid:
      body-width: 1200px     # Max width for body content
      margin-width: 0px      # No margins for full-width elements

editor: visual